// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_REAL_API_KEY_IF_KNOWN', // We might need to find this elsewhere or ask the user
    appId: '1:115852975562:web:b74f3b39c286cc5acd4333',
    messagingSenderId: '115852975562',
    projectId: 'localartisan-7a177',
    authDomain: 'localartisan-7a177.firebaseapp.com',
    storageBucket: 'localartisan-7a177.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_REAL_API_KEY_IF_KNOWN',
    appId: '1:115852975562:android:fe25c02171bda3c4cd4333',
    messagingSenderId: '115852975562',
    projectId: 'localartisan-7a177',
    storageBucket: 'localartisan-7a177.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0cl0SrIKqrodnhYmkM3XjqS3Uc5qPrj4',
    appId: '1:115852975562:ios:b0f37706aa164d5fcd4333',
    messagingSenderId: '115852975562',
    projectId: 'localartisan-7a177',
    storageBucket: 'localartisan-7a177.firebasestorage.app',
    iosBundleId: 'com.example.artisanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0cl0SrIKqrodnhYmkM3XjqS3Uc5qPrj4',
    appId: '1:115852975562:ios:b0f37706aa164d5fcd4333',
    messagingSenderId: '115852975562',
    projectId: 'localartisan-7a177',
    storageBucket: 'localartisan-7a177.firebasestorage.app',
    iosBundleId: 'com.example.artisanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0cl0SrIKqrodnhYmkM3XjqS3Uc5qPrj4',
    appId: '1:115852975562:web:0458d35d6a5c2863cd4333',
    messagingSenderId: '115852975562',
    projectId: 'localartisan-7a177',
    authDomain: 'localartisan-7a177.firebaseapp.com',
    storageBucket: 'localartisan-7a177.firebasestorage.app',
  );
}
